Models/EmpAttendace.cs
namespace RemoteEmpoyeeManagementSystem.Models
{
    public class EmpAttendace
    {
        public string EmpName { get; set; }
        public int EmpId { get; set; }

        public DateTime? InTime { get; set; }
        public bool IsChckInDisabled { get; set; }

        public DateTime? OutTime { get; set; }
        public bool IschckOutDisabled { get; set; }

        public int AttendanceId { get;  set; }
        
    }
}

Models/ErrorViewModel.cs
namespace RemoteEmpoyeeManagementSystem.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/IEmpAttendaceRepository.cs
namespace RemoteEmpoyeeManagementSystem.Models
{
    public interface IEmpAttendaceRepository
    {
        List<EmpAttendace> GetEmpAttendace();
        List<EmpAttendace> MarkEmpAtendace(int id);

    }
}

Models/MockEmpAttendaceRepository.cs
namespace RemoteEmpoyeeManagementSystem.Models
{
    public class MockEmpAttendaceRepository : IEmpAttendaceRepository
    {
        private List<EmpAttendace> _empAttendaces;
        public MockEmpAttendaceRepository()
        {
            _empAttendaces = new List<EmpAttendace>()
             {
                new EmpAttendace {EmpName="omkar", AttendanceId = 1, EmpId = 1, OutTime = DateTime.Now, InTime = DateTime.Now },
                 new EmpAttendace() {EmpName="omkar", AttendanceId = 2, EmpId = 1, OutTime = DateTime.Now, InTime = DateTime.Now },
                 new EmpAttendace() {EmpName="omkar", AttendanceId = 3, EmpId = 1, InTime = DateTime.Now }    
             };

         }
        public List<EmpAttendace> GetEmpAttendace()
        {
            try
            {
                EmpAttendace lastRow = _empAttendaces.LastOrDefault();
                if (string.IsNullOrEmpty(Convert.ToString(lastRow.OutTime)))
                {
                    lastRow.IsChckInDisabled = true;
                }
                return _empAttendaces;
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public List<EmpAttendace> MarkEmpAtendace(int id)
        { 
            EmpAttendace LastRow=_empAttendaces.LastOrDefault();
            if (LastRow.OutTime !=null && LastRow.OutTime <= DateTime.Now)
            {
                Random rnd = new Random();
                _empAttendaces.Add(new EmpAttendace { AttendanceId = rnd.Next(), EmpName = "omkar", InTime = DateTime.Now,IsChckInDisabled=true,OutTime=null });
                
                
            }
            else if(LastRow.InTime !=null && LastRow.OutTime==null)
            {
                LastRow.OutTime = DateTime.Now;
                LastRow.IschckOutDisabled = true;
                LastRow.IsChckInDisabled = false;
            }
            return _empAttendaces;
        }
    }
}

Models/UserLogin.cs
using System.ComponentModel.DataAnnotations;

namespace RemoteEmpoyeeManagementSystem.Models
{
    public class UserLogin
    {
        [Required]
        [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$",ErrorMessage ="Enter User ID In Given format")]
        public string UserId { get; set; }
        [Required]
        [MinLength(8 ,ErrorMessage ="Password Must Contain 8 Characters")]
        public string Password { get; set; }
    }
}

Controllers/AttendanceController.cs
using Microsoft.AspNetCore.Mvc;
using RemoteEmpoyeeManagementSystem.Models;

namespace RemoteEmpoyeeManagementSystem.Controllers
{
    public class AttendanceController : Controller
    {
        private readonly IEmpAttendaceRepository _empAttendanceRepository;
        private readonly ILogger _logger;
        public AttendanceController(IEmpAttendaceRepository empAttendaceRepository, ILogger<AttendanceController> logger)
        {
            _empAttendanceRepository = empAttendaceRepository;
            _logger = logger;
        }
        public IActionResult Index()
        {
           var attendaces= _empAttendanceRepository.GetEmpAttendace();
            _logger.LogInformation("index attendacne controller");
            return View(attendaces);
        }
        [HttpPost]
        public IActionResult MarkAttedance()
        {
           
            var empatt= _empAttendanceRepository.MarkEmpAtendace(1);
            return View("Index",empatt);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RemoteEmpoyeeManagementSystem.Models;
using System.Diagnostics;

namespace RemoteEmpoyeeManagementSystem.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            
            _logger = logger;
        }
        [HttpGet]
        public IActionResult Index()
        {
            _logger.LogInformation("hello ilogger");
            return View();
        }
        [HttpPost]
     
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using RemoteEmpoyeeManagementSystem.Models;

namespace RemoteEmpoyeeManagementSystem.Controllers
{
    public class LoginController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index(UserLogin credentials)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("Index","Home");
            }
            else
            {
               return View(); 
            }
            
        }
    }
}

Views/Attendance/Index.cshtml
@model IEnumerable<RemoteEmpoyeeManagementSystem.Models.EmpAttendace>
<div class="container mb-3">
    <div class="container-lg">
        <h3>Mark Attendance</h3>
    </div>
</div>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Id</th>
            <th scope="col">In time</th>
            <th scope="col">Out Time</th>
            <th scope="col">Attendance id</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var attdc in Model)
        {

            <tr>
                <td scope="row">@attdc.EmpName</td>
                <td>@attdc.EmpId</td>
                <td>@attdc.InTime</td>
                <td>@attdc.OutTime</td>
                <td>@attdc.AttendanceId</td>
            </tr>
        }
    </tbody>
    <div class="container">
        <div class="row">
            <form asp-controller="Attendance" asp-action="MarkAttedance" method="post">
                <label for="Userid" class="form-label">Click Below To mark Attendance</label>
                    
                <div class="mx-auto" style="width: 700px;" @Html.DisabledIf(@Model.LastOrDefault().IsChckInDisabled)>
                    <div class="bg-secondary text-white p-2">
                        <button type="submit" class="btn btn-primary form-control" >Check In</button>
                    </div>
                </div>
                <div class="mx-auto" style="width: 700px;" @Html.DisabledIf(@Model.LastOrDefault().IschckOutDisabled)>
                    <div class="bg-secondary text-white p-2">
                        <button type="submit" class="btn btn-primary form-control">Check Out</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Login/Index.cshtml
@model UserLogin
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/twitter-bootstrap/css/bootstrap.rtl.css" rel="stylesheet" />
    <link href="~/lib/twitter-bootstrap/css/bootstrap.rtl.min.css" rel="stylesheet" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0 shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Employee Login</title>
    <link rel="stylesheet" href="./style.css">
    <link rel="icon" href="./favicon.ico" type="image/x-icon">
</head>
<body >
    <script type="text/javascript">
        function ValidateInput()
        {
            var userid =document.getElementById("userid").value;
            var password = document.getElementById("password").value;
            var valSum = document.getElementById("valSum");

            if(userid=='' && password=='')
            {
                valSum.innerHTML="please enter id and password";
                return false;
            }           
            
        }
        </script>
    <style type="text/css">
       body {
            background-image: url('~/wwwroot/images/workerweb.jpg');
            margin: 0;
        }
    </style>
    <main>
        <form asp-controller="Login" asp-action="Index" method="post">
        <div class="container col-sm-auto col-lg-6  col-md-auto " >
            <div class="mb-3 mt-3 align-content-center row-cols-4">
                <label for="userid" class="form-label">USERID</label>
                <input type="email" class="form-control" id="userid"  asp-for="UserId" placeholder="name@example.com">
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="mb-3 align-content-lg-stretch row-cols-4">
                <label for="password" class="form-label">PASSWORD</label>
                <input type="password" class="form-control" id="password" placeholder="" asp-for="Password">
                 <span asp-validation-for="Password" class="text-danger"></span>

            </div>
            <div id="valSum" asp-validation-summary="All" class="text-danger"></div>
            <div class="mb-3 row-cols-4">
                <button type="submit" class="btn btn-primary form-control" onclick="return ValidateInput()" >SUBMIT</button>
            </div>
        </div>
       </form>
        
    </main>
    <script src="index.js"></script>
</body>
</html>

Views/Login/Login.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Website</title>
    <link rel="stylesheet" href="./style.css">
    <link rel="icon" href="./favicon.ico" type="image/x-icon">
  </head>
  <body>
    <main>
        <h1>You are logged in </h1>  
    </main>
    <script src="index.js"></script>
  </body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RemoteEmpoyeeManagementSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/CustomStyle.css"/>
    <link rel="stylesheet" href="~/MVCdemo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img style="height:30px; width:30px;" src="~/images/attendance-management-system.jpg"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">HOME</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Attendance" asp-action="Index">ATTENDANCE</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">DASHBOARD</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">REPORTS</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Remote Empoyee Management System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>